name: Build PS5 App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest # Launches a real Arch Linux environment directly
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Prerequisites
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git base-devel cmake python

      - name: Run Build Script
        run: |
          chmod +x ./tools/bootstrap.sh
          ./tools/bootstrap.sh

      - name: Upload Finished PS5 App Folder
        uses: actions/upload-artifact@v4
        with:
          name: rpcs3-ps5-build
          path: build/
